### ISSUE TITLE
Some page content not visible, likely because content was styled assuming white background

### ISSUE THREAD

**Issue by gonzotheweirdo** [vitaly-zdanevich/wikipedia-userstyle-dark-minimum#1]
example page:
https://en.wikipedia.org/wiki/Digital_root

formulas are blacked out. Maybe formula graphic content is black-on-clear, which renders invisible.

**Comment by vitaly-zdanevich** [comment]
Thank you, now formulas will be displayed not as images but as readable text:

![image](https://user-images.githubusercontent.com/3514015/100489437-3785d200-3125-11eb-8b23-1d457c00ee5d.png)
