### ISSUE TITLE
Unable to undo

### ISSUE THREAD

**Issue by timgianitsos** [vitaly-zdanevich/wikipedia-userstyle-dark-minimum#3]
This CSS seems to remove the ability to view preferences (there is no longer a bar on the top right). How can this theme be undone?

**Comment by vitaly-zdanevich** [comment]
By this link https://en.wikipedia.org/wiki/Special:MyPage/vector.css

**Comment by otaviopires** [comment]
This is still happening, there's no button on the page to enable edition the custom css.

**Comment by vitaly-zdanevich** [comment]
I prefer simplicity, you can edit custom CSS by the link above.

**Comment by timgianitsos** [comment]
Put `&action=edit` at the end of the URL [to edit](https://www.quora.com/When-will-we-get-a-black-dark-official-theme-for-Wikipedia?share=1).

I suggest that a warning be put in the README as most people who use this will have no idea how to undo.

**Comment by vitaly-zdanevich** [comment]
Returned preferences back.
