### ISSUE TITLE
#3 is still happening

### ISSUE THREAD

**Issue by otaviopires** [vitaly-zdanevich/wikipedia-userstyle-dark-minimum#4]
This is still happening, there's no button on the page to enable edition the custom css.

#3 

![image](https://user-images.githubusercontent.com/1145551/112540666-368e4580-8d91-11eb-86c6-1928df18cec8.png)

![image](https://user-images.githubusercontent.com/1145551/112540690-3f7f1700-8d91-11eb-8616-329d578dc4a1.png)

**Comment by vitaly-zdanevich** [comment]
You can edit custom CSS by this link https://en.wikipedia.org/wiki/Special:MyPage/vector.css

**Comment by vitaly-zdanevich** [comment]
Also now you can use this with browser extension Stylus https://github.com/openstyles/stylus
